# RT-Thread building script for component
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []

LIBPATH = [cwd]
LIBS = []
if GetDepend(['SOC_SERIES_N9H30']):
	if rtconfig.CROSS_TOOL == 'keil':
		LIBS += ['NUemWin_N9H30_Keil']
	elif rtconfig.CROSS_TOOL == 'gcc':
		LIBS += ['libNUemWin_N9H30_GCC']

CPPPATH = [cwd + '/../Include']

group = DefineGroup('NUemWin', src, depend = ['PKG_USING_NUEMWIN'], CPPPATH = CPPPATH, LIBS = LIBS, LIBPATH=LIBPATH)

Return('group')
