import os
from building import *

cwd = GetCurrentDir()
objs = []

if GetDepend('PKG_USING_NUEMWIN_GUIDEMO'):
    path = os.path.join(cwd, 'GUIDemo')
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

if GetDepend('PKG_USING_NUEMWIN_SIMPLEDEMO'):
    path = os.path.join(cwd, 'SimpleDemo')
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')