import os
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = Glob('*.c')
objs = []

if GetDepend('PKG_USING_NUEMWIN_GUIDEMO'):
    path = os.path.join(cwd, 'GUIDemo')
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join('GUIDemo', 'SConscript'))

if GetDepend('PKG_USING_NUEMWIN_SIMPLEDEMO'):
    path = os.path.join(cwd, 'SimpleDemo')
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join('SimpleDemo', 'SConscript'))

group = DefineGroup('NUemWin', src, depend = [''], CPPPATH = CPPPATH)
objs = objs + group

Return('objs')